### ISSUE TITLE
Detect duplicate YAML keys

### ISSUE THREAD

**Issue by adamgreig** [stm32-rs/svdtools#63]
Currently duplicate keys are silently ignored, which is a common cause of errors.

In principle any conforming YAML parser should emit a warning in such a situation, but PyYAML [does](https://github.com/yaml/pyyaml/issues/165) [not](https://github.com/yaml/pyyaml/issues/41). A [workaround](https://gist.github.com/pypt/94d747fe5180851196eb) might be possible.

**Comment by burrbull** [comment]
Could we create tool and add it to CI?
